name: Check all markdown links monthly
on: 
  push:
    branches:
    - main
  schedule:
  # Run every first day of the month at 8am
  - cron: "0 08 1 * *"

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: 'yes'
        use-verbose-mode: 'yes'
        base-branch: 'main'
        folder-path: 'docs'
