# This is a basic workflow to help you get started with Actions

name: xlab-docs-CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events
  push:
    paths:
      - docs/**
  pull_request:
    types: [opened, synchronize]
    paths:
      - docs/**

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  check-links:
    runs-on: ubuntu-latest
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # checks for broken links using muffet through my-broken-link-checker
      - name: Check broken links
        env:
          INPUT_URL: https://${{ github.event.repository.owner.name }}.github.io/${{ github.event.repository.name }}
          INPUT_PAGES_PATH: .
          INPUT_CMD_PARAMS: --buffer-size=8192 --max-connections=10 --color=always --skip-tls-verification
        run: |
          ln -s docs/ ${{ github.event.repository.name }}
          wget -qO- https://raw.githubusercontent.com/ruzickap/action-my-broken-link-checker/v1/entrypoint.sh | bash







