name: Jekyll Deploy

on:
  push:
    branches:
      - jekyll-clean

jobs:
  build_and_deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: GitHub Checkout
        uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Build & Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAGES_TOKEN }}
        run: bash ${GITHUB_WORKSPACE}/.github/deploy.sh