name: Jekyll Deploy

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: GitHub Checkout Theme
        uses: actions/checkout@v2
        with:
          repository: burglabs/kb-jekyll
      - name: GitHub Checkout Content
        uses: actions/checkout@v2
        with:
          path: tmp-content
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.1
          bundler-cache: true
      - name: Build & Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAGES_TOKEN }}
        run: bash ${GITHUB_WORKSPACE}/tmp-content/.github/deploy.sh